# -*- coding: utf-8 -*-
"""bank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V3Ycl3i-Hdhi5wpvdf4MLnTOzDJrjEvr
"""

balance = 0
transactions = []
PASSWORD = "arpita"
def login():
    attempts = 5
    while attempts > 0:
        pwd = input("Enter password: ")
        if pwd == PASSWORD:
            print("Login Successful")
            return True
        else:
            attempts -= 1
            print("Wrong password. Left:", attempts)
    print("Account Locked")
    return False
def deposit(balance):
    amount = float(input("Enter amount: "))
    if amount > 0:
        balance += amount
        transactions.append("Deposited: " + str(amount))
        print("Money Added")
    else:
        print("Invalid Amount")
    return balance
def withdraw(balance):
    amount = float(input("Enter amount: "))
    if amount > balance:
        print("Not Enough Balance")
    elif amount <= 0:
        print("Invalid Amount")
    else:
        balance -= amount
        transactions.append("Withdrawn: " + str(amount))
        print("Money Withdrawn")
    return balance
def check_balance(balance):
    print("Your Balance:", balance)
def view_transactions():
    if len(transactions) == 0:
        print("No Record Found")
    else:
        for t in transactions:
            print(t)

def menu():
    print("1.Deposit")
    print("2.Withdraw")
    print("3.Balance")
    print("4.History")
    print("5.Exit")
    return input("Choose: ")
if login():
    while True:
        choice = menu()
        if choice == "1":
            balance = deposit(balance)
        elif choice == "2":
            balance = withdraw(balance)
        elif choice == "3":
            check_balance(balance)
        elif choice == "4":
            view_transactions()
        elif choice == "5":
            print("Thank You")
            break
        else:
            print("Wrong Choice")